# Generated by Django 2.2.2 on 2019-07-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190626_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identificacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
