# Generated by Django 2.2.2 on 2019-07-02 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_pontoturistico_identi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identificacao',
            name='num',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
