# Generated by Django 2.2.2 on 2019-07-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190702_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identificacao',
            name='num',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
