# Generated by Django 2.2.2 on 2019-07-10 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190707_1531'),
        ('core', '0010_auto_20190705_1345'),
    ]

    operations = [
    ]
