# Generated by Django 2.0.7 on 2019-06-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='strap',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
