# Generated by Django 2.2.2 on 2019-06-27 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_comentario_strap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='strap',
        ),
    ]
